### ISSUE TITLE
请教一个关于ngx_lua_waf黑白名单支持IP地址段的问题！

### ISSUE THREAD

**Issue by nightwiz** [wklken/vim-for-server#3]
RickieL你好！不好意思在这里提了一个不相关的问题。
想请教下你关于ngx_lua_waf的ip黑白名单地址段的这个功能您实现了吗！
在ngx_lua_waf项目哪里看到你提交的代码，假如我需要实现这个功能，需要把代码添加到哪里呢？
希望能够得到你的回复，万分感谢！！

**Comment by wklken** [comment]
发错人了....我不是RickieL >_<#

**Comment by nightwiz** [comment]
噗~I am sorry……
