### ISSUE TITLE
请问作者，这个 server 版的vim是弃坑了么？ 

### ISSUE THREAD

**Issue by programscape** [wklken/vim-for-server#4]

**Comment by wklken** [comment]
并没有, 只是不带插件版本的基础配置相对稳定很多
近一年还有部分配置在原`k-vim`, 会找个时间同步过来, 测试后发布到`server`版本

**Comment by programscape** [comment]
Get，K-vim 对于偶尔线上改代码还是太重了，k-vim 刚刚好，thanks
